export const publicKey = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCppjLaTSRGhVqZ4UGn3TaALP2r
vt0Ew3HSRF8Edg3TE/nHHkRZaW/FKdECdGRHOYBn724BWwbBTdn/yfmBi4udzHnV
kcOeVVT4sf/vza6cZYYzd8Ej9ReDvxgNXnDcIaLUHaT7S7QBq7jBZ+J5E9aye0S3
i1b/+s3BBxrdPtkM7wIDAQAB
-----END PUBLIC KEY-----`;
