// images
export {default as DeedLogoImg} from 'assets/img/deed_logo.png';
export {default as dashboardImage} from 'assets/img/dashboard.png';
export {default as logo} from 'assets/img/logo.png';
export {default as defaultUser} from 'assets/svg/user_default.svg';
export {default as chatImageDefault} from 'assets/img/chatImageDefault.png';
// svg
export {default as DoctorIcon} from 'assets/svg/Doctor';
export {default as HospitalIcon} from 'assets/svg/Hospital';
export {default as CalenderIcon} from 'assets/svg/Calendar';
export {default as CheckedIcon} from 'assets/svg/Checked';
export {default as ParkingIcon} from 'assets/svg/Parking';
export {default as ThinkingIcon} from 'assets/svg/Thinking';
export {default as MinusIcon} from 'assets/svg/Minus';
export {default as CloseIcon} from 'assets/svg/Closed';
export {default as PlusIcon} from 'assets/svg/Plus';
export {default as maintenanceImg} from 'assets/img/maintenance.svg';
export {default as UserIcon} from 'assets/svg/User';
export {default as User1Icon} from 'assets/svg/User1';
export {default as User2Icon} from 'assets/svg/User2';
export {default as ErrorMessage} from 'assets/svg/ErrorMessage';
export {default as ServerErrorIcon} from 'assets/svg/ServerError';
export {default as EducationIcon} from 'assets/svg/Education';
export {default as ViewIcon} from 'assets/svg/View';
export {default as EmptyBoxIcon} from 'assets/svg/EmptyBox';
export {default as DiseaseIcon} from 'assets/svg/Disease';
export {default as SupportIcon} from 'assets/svg/Support';
export {default as StethoscopeIcon} from 'assets/svg/Stethoscope';
export {default as Drop} from 'assets/svg/drop';
export {default as ReplyIcon} from 'assets/svg/Reply';
export {default as EmptyMessage} from 'assets/svg/EmptyMessage';
export {default as FollowupIcon} from 'assets/svg/Followup';
export {default as RequiredIcon} from 'assets/svg/Required';
export {default as MemoirIcon} from 'assets/svg/Memoir';
export {default as LowIcon} from 'assets/svg/Low';
export {default as NoVisitIcon} from 'assets/svg/NoVisit';
export {default as RecordingIcon} from 'assets/svg/Recording';
export {default as RecordingStopIcon} from 'assets/svg/Stop';
export {default as PatientIcon} from 'assets/svg/Patient';
export {default as EmptyList} from 'assets/svg/EmptyList';
export {default as PrescriptionIcon} from 'assets/svg/Prescription';

// constants
export * from 'assets/constants/Education';
export * from 'assets/constants/Orders';
export {default as is_active} from 'assets/constants/Product';
export * from 'assets/constants/Questions';
export * from 'assets/constants/Setting';
export * from 'assets/constants/Message';
export {default as visitStatus} from 'assets/constants/Visit';
export {VisitTypes} from 'assets/constants/Visit';
export * from 'assets/constants/User';
export * from 'assets/constants/commen';
export * from 'assets/constants/dashboard';
